import 'package:schemaz_model/schemaz_model.dart';

class DartGenerator {
  /// Generates idiomatic Dart code from Schemaz AST declarations.
  static String generate(List<Declaration> declarations) {
    final buffer = StringBuffer();
    buffer.writeln('// Generated by Schemaz Compiler. DO NOT EDIT.');
    buffer.writeln("import 'package:schemaz_core/schemaz_core.dart';");
    buffer.writeln();

    for (final decl in declarations) {
      if (decl is SchemaDeclaration) {
        _generateSchemaClass(buffer, decl);
      } else if (decl is FunctionDeclaration) {
        _generateFunction(buffer, decl);
      }
    }

    return buffer.toString();
  }

  static void _generateSchemaClass(
      StringBuffer buffer, SchemaDeclaration decl) {
    final extendsClause =
        decl.supertype != null ? 'extends ${decl.supertype} ' : '';

    buffer.writeln('class ${decl.name} $extendsClause{');

    for (final prop in decl.properties) {
      final type = prop.ranges.isNotEmpty ? prop.ranges.first : 'dynamic';
      final nullableStr = prop.isNullable ? '?' : '';
      buffer.writeln('  final $type$nullableStr ${prop.name};');
    }

    buffer.writeln();
    buffer.write('  const ${decl.name}({');
    for (final prop in decl.properties) {
      final requiredStr = prop.isNullable ? '' : 'required ';
      buffer.write('${requiredStr}this.${prop.name}, ');
    }
    buffer.writeln('});');

    // Generate static .schema descriptor
    buffer.writeln();
    buffer.writeln('  static const SchemaDescriptor schema = SchemaDescriptor(');
    buffer.writeln('    id: "${decl.schemaUri ?? decl.name}",');
    buffer.writeln('    name: "${decl.name}",');
    buffer.writeln('  );');

    buffer.writeln('}');
    buffer.writeln();
  }

  static void _generateFunction(
      StringBuffer buffer, FunctionDeclaration decl) {
    final returnType = decl.returnType ?? 'void';
    buffer.write('$returnType ${decl.name}(');

    final params = decl.parameters.entries
        .map((e) => '${e.value} ${e.key}')
        .join(', ');
    buffer.writeln('$params) {');
    buffer.writeln('  // Implementation stub');
    buffer.writeln('}');
    buffer.writeln();
  }
}
