import 'package:schemaz_model/schemaz_model.dart';

class DartGenerator {
  /// Generates idiomatic Dart code from Schemaz AST declarations with schema capability methods.
  static String generate(List<Declaration> declarations) {
    final buffer = StringBuffer();
    buffer.writeln('// Generated by Schemaz Compiler. DO NOT EDIT.');
    buffer.writeln("import 'package:schemaz_core/schemaz_core.dart';");
    buffer.writeln();

    for (final decl in declarations) {
      if (decl is SchemaDeclaration) {
        _generateSchemaClass(buffer, decl);
      } else if (decl is FunctionDeclaration) {
        _generateFunction(buffer, decl);
      }
    }

    return buffer.toString();
  }

  static void _generateSchemaClass(
      StringBuffer buffer, SchemaDeclaration decl) {
    final extendsClause =
        decl.supertype != null ? 'extends ${decl.supertype} ' : '';

    buffer.writeln('class ${decl.name} $extendsClause{');

    for (final prop in decl.properties) {
      final type = prop.ranges.isNotEmpty ? prop.ranges.first : 'dynamic';
      final nullableStr = prop.isNullable ? '?' : '';
      buffer.writeln('  final $type$nullableStr ${prop.name};');
    }

    buffer.writeln();
    buffer.write('  const ${decl.name}({');
    for (final prop in decl.properties) {
      final requiredStr = prop.isNullable ? '' : 'required ';
      buffer.write('${requiredStr}this.${prop.name}, ');
    }
    buffer.writeln('});');

    // Generate static .schema descriptor
    buffer.writeln();
    buffer.writeln('  static const SchemaDescriptor schema = SchemaDescriptor(');
    buffer.writeln('    id: "${decl.schemaUri ?? decl.name}",');
    buffer.writeln('    name: "${decl.name}",');
    buffer.writeln('  );');
    buffer.writeln();

    // Generate toJson()
    buffer.writeln('  Map<String, dynamic> toJson() => {');
    for (final prop in decl.properties) {
      buffer.writeln('    "${prop.name}": ${prop.name},');
    }
    buffer.writeln('  };');
    buffer.writeln();

    // Generate toJsonLd()
    buffer.writeln('  Map<String, dynamic> toJsonLd() => {');
    buffer.writeln('    "@context": "https://schema.org",');
    buffer.writeln('    "@type": "${decl.name}",');
    for (final prop in decl.properties) {
      buffer.writeln('    "${prop.name}": ${prop.name},');
    }
    buffer.writeln('  };');
    buffer.writeln();

    // Generate fromJson()
    buffer.writeln('  factory ${decl.name}.fromJson(Map<String, dynamic> json) => ${decl.name}(');
    for (final prop in decl.properties) {
      final type = prop.ranges.isNotEmpty ? prop.ranges.first : 'dynamic';
      final nullableStr = prop.isNullable ? '?' : '';
      final castExpr = type != 'dynamic' ? ' as $type$nullableStr' : '';
      buffer.writeln('    ${prop.name}: json["${prop.name}"]$castExpr,');
    }
    buffer.writeln('  );');

    buffer.writeln('}');
    buffer.writeln();
  }

  static void _generateFunction(
      StringBuffer buffer, FunctionDeclaration decl) {
    final returnType = decl.returnType ?? 'void';
    buffer.write('$returnType ${decl.name}(');

    final params = decl.parameters.entries
        .map((e) => '${e.value} ${e.key}')
        .join(', ');
    buffer.writeln('$params) {');
    if (returnType == 'void') {
      buffer.writeln('  // Implementation stub');
    } else {
      buffer.writeln('  throw UnimplementedError();');
    }
    buffer.writeln('}');
    buffer.writeln();
  }
}
