// Generated by Schemaz Compiler. DO NOT EDIT.
import 'package:schemaz_core/schemaz_core.dart';

class LocalizedPerson {
  final LocalizedString name;
  final LocalizedString? description;

  const LocalizedPerson({required this.name, this.description, });

  static const SchemaDescriptor schema = SchemaDescriptor(
    id: "https://schema.org/Person",
    name: "LocalizedPerson",
  );

  Map<String, dynamic> toJson() => {
    "name": name,
    "description": description,
  };

  Map<String, dynamic> toJsonLd({Object? context}) => {
    "@context": context ?? "https://schema.org",
    "@type": "LocalizedPerson",
    "name": name?.toJsonLd(),
    "description": description?.toJsonLd(),
  };

  factory LocalizedPerson.fromJson(Map<String, dynamic> json) => LocalizedPerson(
    name: LocalizedString.fromJsonLd(json["name"]),
    description: json["description"] != null ? LocalizedString.fromJsonLd(json["description"]) : null,
  );
}
