// Generated by Schemaz Compiler. DO NOT EDIT.
import 'package:schemaz_core/schemaz_core.dart';

class Person {
  final String name;
  final String? email;

  const Person({required this.name, this.email, });

  static const SchemaDescriptor schema = SchemaDescriptor(
    id: "https://schema.org/Person",
    name: "Person",
  );

  Map<String, dynamic> toJson() => {
    "name": name,
    "email": email,
  };

  Map<String, dynamic> toJsonLd({Object? context}) => {
    "@context": context ?? "https://schema.org",
    "@type": "Person",
    "name": name,
    "email": email,
  };

  factory Person.fromJson(Map<String, dynamic> json) => Person(
    name: json["name"] as String,
    email: json["email"] as String?,
  );
}

String greet(Person person) {
  throw UnimplementedError();
}
