// Generated by Schemaz Compiler. DO NOT EDIT.
import 'package:schemaz_core/schemaz_core.dart';

class Product {
  final String name;
  final double price;

  const Product({required this.name, required this.price, });

  static const SchemaDescriptor schema = SchemaDescriptor(
    id: "https://schema.org/Product",
    name: "Product",
  );

  Map<String, dynamic> toJson() => {
    "name": name,
    "price": price,
  };

  Map<String, dynamic> toJsonLd() => {
    "@context": "https://schema.org",
    "@type": "Product",
    "name": name,
    "price": price,
  };

  factory Product.fromJson(Map<String, dynamic> json) => Product(
    name: json["name"] as String,
    price: json["price"] as double,
  );
}

double calculateTax(Product product) {
  throw UnimplementedError();
}
