import '../core/schema.dart';
import '../core/type.dart';

/// Transpiles Schemaz schemas, types, and nodes into clean, idiomatic Dart code
/// for Kotlin/Java style interop between Dart and Schemaz.
class DartCodeGenerator {
  /// Generate Dart class definitions for a given list of Schemaz Schemas.
  String generateDartClass(Schema schema) {
    final buffer = StringBuffer();

    buffer.writeln("// Generated by Schemaz Dart Code Generator");
    buffer.writeln("import 'package:schemaz/schemaz.dart' as sz;");
    buffer.writeln();

    final className = _capitalize(schema.name);
    final parentClassName = schema.parents.isNotEmpty ? _capitalize(schema.parents.first.name) : null;

    if (parentClassName != null) {
      buffer.writeln("class $className extends $parentClassName {");
    } else {
      buffer.writeln("class $className {");
    }

    // Fields
    schema.properties.forEach((propName, propDef) {
      final dartType = _mapSchemazTypeToDart(propDef.type);
      buffer.writeln("  final $dartType? $propName;");
    });

    buffer.writeln();

    // Constructor
    buffer.write("  $className({");
    schema.properties.forEach((propName, propDef) {
      buffer.write("this.$propName, ");
    });
    buffer.writeln("});");

    buffer.writeln();

    // Convert from Schemaz Node
    buffer.writeln("  factory $className.fromNode(sz.Node node) {");
    buffer.writeln("    return $className(");
    schema.properties.forEach((propName, propDef) {
      final dartType = _mapSchemazTypeToDart(propDef.type);
      buffer.writeln("      $propName: node.get('$propName') as $dartType?,");
    });
    buffer.writeln("    );");
    buffer.writeln("  }");

    buffer.writeln();

    // Convert to Schemaz Node
    buffer.writeln("  sz.Node toNode(sz.SchemaRegistry registry) {");
    buffer.writeln("    final schema = registry.lookupSchema('${schema.name}') ??");
    buffer.writeln("        sz.Schema(name: '${schema.name}', uri: '${schema.uri ?? ''}');");
    buffer.writeln("    return sz.Node(");
    buffer.writeln("      schema: schema,");
    buffer.writeln("      properties: {");
    schema.properties.forEach((propName, _) {
      buffer.writeln("        '$propName': $propName,");
    });
    buffer.writeln("      },");
    buffer.writeln("    );");
    buffer.writeln("  }");

    buffer.writeln("}");

    return buffer.toString();
  }

  String _mapSchemazTypeToDart(SchemazType type) {
    if (type == PrimitiveType.text) return 'String';
    if (type == PrimitiveType.integer) return 'int';
    if (type == PrimitiveType.float) return 'double';
    if (type == PrimitiveType.boolean) return 'bool';
    if (type == PrimitiveType.dateTime) return 'DateTime';
    if (type is ListType) return 'List<${_mapSchemazTypeToDart(type.elementType)}>';
    if (type is MapType) return 'Map<String, dynamic>';
    return 'dynamic';
  }

  String _capitalize(String str) {
    if (str.isEmpty) return str;
    return str[0].toUpperCase() + str.substring(1);
  }
}
